module.exports = {
  apps: [
    {
      name:               'ltc-api',
      script:             'server/index.js',
      instances:          1,
      autorestart:        true,
      watch:              false,
      max_memory_restart: '512M',
      restart_delay:      5000,
      max_restarts:       10,
      env: { NODE_ENV: 'production' },
      error_file: 'logs/api-error.log',
      out_file:   'logs/api-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name:               'ltc-bot',
      script:             'bot/index.js',
      instances:          1,
      autorestart:        true,
      watch:              false,
      max_memory_restart: '256M',
      restart_delay:      5000,
      max_restarts:       10,
      env: { NODE_ENV: 'production' },
      error_file: 'logs/bot-error.log',
      out_file:   'logs/bot-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
  ],
};
